# Generated by Django 4.1.2 on 2024-03-30 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emailwithattachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_email_address', models.EmailField(max_length=254)),
                ('sender_email_password', models.CharField(max_length=50)),
                ('receiver_name', models.CharField(max_length=50)),
                ('receiver_email_address', models.EmailField(max_length=254)),
                ('stegano_image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
