# Generated by Django 4.1.2 on 2024-04-02 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_emailwithattachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailwithattachment',
            name='stegano_image',
            field=models.ImageField(upload_to='stegano_images/'),
        ),
    ]
